# What Is a Relation?

In the previous notebook we learned what a database is. Now we will see how data is
organised within it.

In a relational database, the central concept is the **relation**, which in practice
is a **table**.

## Example

Let us look again at the `artist` table from Chinook:

In [2]:
from rel_db_learning import get_chinook_connection, run_sql

chinook = get_chinook_connection()
run_sql("SELECT * FROM artist LIMIT 5", chinook)

   artist_id               name
0          1              AC/DC
1          2             Accept
2          3          Aerosmith
3          4  Alanis Morissette
4          5    Alice In Chains

Notice the structure:

- The table is called **`artist`** — this is the name of the relation.
- It has two **columns**: `artistid` and `name`. Each column is called an **attribute**
  and has a specific data type (number, text, etc.).
- Each **row** of the table is called a **tuple** and represents a specific artist.

## Terminology

In relational databases we use the following terms:

| Everyday term | Formal term |
|---|---|
| Table | Relation |
| Column | Attribute |
| Row | Tuple |
| Kind of data | Type (Domain/Data type) |

We will use both terms the same way. When we say "table Album" we mean exactly
the same as "relation Album".

## Schema vs Instance

Two important concepts:

- The **schema** is the **structure** of the table: which columns it has, their types,
  and which rules apply. It rarely changes.
- The **instance** is the **data** that exists in the table at a particular moment.
  It changes continuously (new records, deletions, updates).

For example, the `artist` table has the same schema (columns artistid, name) regardless
of whether it contains 10 or 10,000 artists.

## Multiple tables, one database

A database does not have just one table, it has many and they are related to each other.
Let us look at another Chinook table, `album`:

In [3]:
run_sql("SELECT * FROM album LIMIT 10", chinook)

   album_id                                  title  artist_id
0         1  For Those About To Rock We Salute You          1
1         2                      Balls to the Wall          2
2         3                      Restless and Wild          2
3         4                      Let There Be Rock          1
4         5                               Big Ones          3
5         6                     Jagged Little Pill          4
6         7                               Facelift          5
7         8                         Warner 25 Anos          6
8         9         Plays Metallica By Four Cellos          7
9        10                             Audioslave          8

The `album` table contains albums. Each album has:

- Its own **identifier** (`album_id`)
- A **title** (`title`)
- A reference to the **artist** who released it (`artist_id`)

The `artist_id` column in `album` refers to the `artist_id` column in `artist`. This is
how the two tables are **linked**. In latethe next modules we will look in detail at how these
links work.

## How many tables are there?

Chinook consists of 11 tables in total. Let us list them:

In [4]:
run_sql("""
    SELECT table_name 
    FROM information_schema.tables 
    WHERE table_schema = 'public'
    ORDER BY table_name
""", chinook)

        table_name
0            album
1           artist
2         customer
3         employee
4            genre
5          invoice
6     invoice_line
7       media_type
8         playlist
9   playlist_track
10           track

These are all the tables in the database. In the next notebook we will explore them in
detail to understand what each one contains.

## Key takeaways

- A **relation** is a **table** with columns (attributes) and rows (tuples).
- The **schema** is the structure; the **instance** is the data.
- A database consists of **many tables** that may be linked to each other.